ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3
ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
