ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3
ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o