ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3
ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_a3/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
